#coding=utf-8
from selenium import webdriver

def elementInit():
	AN = '//*[@id="AN"]'
	AD = '//*[@id="AD"]'
	PD = '//*[@id="PD"]'
	TIABSTCLM = '//*[@id="TI,ABST,CLM"]'
	TIABST = '//*[@id="TI,ABST"]'
	TI = '//*[@id="TI"]'
	ABST = '//*[@id="ABST"]'
	CLM = '//*[@id="CLM"]'
	DESCR = '//*[@id="DESCR"]'
	PA = '//*[@id="PA"]'
	PATMS = '//*[@id="PATMS"]'
	INN = '//*[@id="INN"]'
	INNTMS = '//*[@id="INNTMS"]'
	LV = '//*[@id="LV"]'
	LLS = '//*[@id="LLS"]'
	SIC = '//*[@id="SIC"]'
	PIC = '//*[@id="PIC"]'
	CPC = '//*[@id="CPC"]'
	SNC = '//*[@id="SNC"]'
	CO = '//*[@id="CO"]'
	ADDR = '//*[@id="ADDR"]'
	PR = '//*[@id="PR"]'
	DAN = '//*[@id="DAN"]'
	AGC = '//*[@id="AGC"]'
	AGTTMS = '//*[@id="AGTTMS"]'
	AGT = '//*[@id="AGT"]'
	IAN = '//*[@id="IAN"]'
	IPN = '//*[@id="IPN"]'
	DEN = '//*[@id="DEN"]'
	TZH = '//*[@id="TZH"]'
	PERIOD = '//*[@id="PERIOD"]'
	REFBYN = '//*[@id="REFBYN"]'
	CLMN = '//*[@id="CLMN"]'
	searchButton = '//*[@id="btnASearch"]'
	return AN,AD,PD,TIABSTCLM,TIABST,TI,ABST,CLM,DESCR,PA,PATMS,INN,INNTMS,LV,LLS,SIC,PIC,CPC,SNC,CO,ADDR,PR,DAN,AGC,AGTTMS,AGT,IAN,IPN,DEN,TZH,PERIOD,REFBYN,CLMN,searchButton